/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Ready */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List generation jobs */
        get: operations["list_generations"];
        put?: never;
        /**
         * Generate synthetic FHIR data
         * @description Submit a spec (a preset, a full spec, or a preset plus overrides). With the `inline` sink the bundles come back in `data` (200); with any file sink a job is queued (202) — poll `GET /generations/{id}` and download from its `artifacts`.
         */
        post: operations["create_generation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generations/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate and resolve a spec without running it */
        post: operations["preview_generation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generations/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a generation job (status, provenance, artifacts) */
        get: operations["get_generation"];
        put?: never;
        post?: never;
        /** Delete a generation job and its artifacts */
        delete: operations["delete_generation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generations/{job_id}/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download one artifact produced by a generation */
        get: operations["download_generation_artifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generations/{job_id}/bundles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The bundles of a finished generation (one line each: patient and resource counts)
         * @description Reads the stored files (JSON, ZIP or NDJSON) so a viewer can draw the data. 410 once the files expire.
         */
        get: operations["list_generation_bundles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generations/{job_id}/bundles/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One FHIR bundle of a finished generation, whole */
        get: operations["get_generation_bundle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configured connectors and what each supports natively */
        get: operations["list_connectors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/{name}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Is the connector usable right now? */
        get: operations["connector_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/{name}/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find the codes to target: search the conditions, procedures, medications... a connector can produce
         * @description Cohorts are targeted by code. Search by words (`q=colonoscopy`, `q=reflux`) and optionally `kind` (condition, procedure, medication, observation, allergy, immunization, device, diagnostic_report); paste the `reference` of the hits into `cohort.conditions` / `cohort.procedures`. The first call per Synthea image takes a few seconds while the index is built, then it is cached.
         */
        get: operations["search_terms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/{name}/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The states, or the cities of one state, a connector can generate people in
         * @description Without `state`: the valid state names. With `state` (any capitalisation): that state's valid city names. `cohort.state` and `cohort.city` must be one of these (capitalisation is corrected automatically).
         */
        get: operations["list_places"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resource-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Named categories of resource types usable in the resource_types slicer (clinical, financial, administrative...) */
        get: operations["list_resource_groups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/slicers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Available slicers with their parameter schemas */
        get: operations["list_slicers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sinks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configured sinks with their parameter schemas */
        get: operations["list_sinks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/specialties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configured specialties (named module groups) */
        get: operations["list_specialties"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preset catalogue */
        get: operations["list_presets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One preset */
        get: operations["get_preset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets/{name}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a preset, optionally with overrides
         * @description Shorthand for POST /generations with `preset` set to the path name.
         */
        post: operations["run_preset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactResponse */
        ArtifactResponse: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /** Size */
            size: number;
            /** Content Type */
            content_type: string;
            /** Download Url */
            download_url: string;
        };
        /** BundleIndexResponse */
        BundleIndexResponse: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["BundleSummary"][];
        };
        /** BundleSummary */
        BundleSummary: {
            /** Index */
            index: number;
            /** Label */
            label: string;
            /** Resources */
            resources: number;
            /** By Type */
            by_type: {
                [key: string]: number;
            };
        };
        /**
         * CohortOverrides
         * @description Same fields as CohortSpec, but nothing is defaulted so 'not supplied' can be
         *     told apart from 'supplied as the default' when merging over a preset.
         */
        CohortOverrides: {
            /** Count */
            count?: number | null;
            /**
             * Seed
             * @description Reproducibility seed; random if omitted (and recorded)
             */
            seed?: number | null;
            /** Gender */
            gender?: ("M" | "F") | null;
            /**
             * Age Range
             * @description [min, max] age in years
             */
            age_range?: [
                number,
                number
            ] | null;
            /** State */
            state?: string | null;
            /** City */
            city?: string | null;
            /**
             * Specialty
             * @description Name of a specialty defined in the connectors config
             */
            specialty?: string | null;
            /** Conditions */
            conditions?: string[] | null;
            /** Procedures */
            procedures?: string[] | null;
            /** Match */
            match?: ("all" | "any") | null;
            /** Medications */
            medications?: string[] | null;
            /** Within */
            within?: ("all" | "any") | null;
            /** Years Of History */
            years_of_history?: number | null;
            /** Only Alive */
            only_alive?: boolean | null;
        };
        /**
         * CohortSpec
         * @description Who gets generated.
         */
        CohortSpec: {
            /**
             * Count
             * @description Number of patients to export
             * @default 1
             */
            count: number;
            /**
             * Seed
             * @description Reproducibility seed; random if omitted (and recorded)
             */
            seed?: number | null;
            /** Gender */
            gender?: ("M" | "F") | null;
            /**
             * Age Range
             * @description [min, max] age in years
             */
            age_range?: [
                number,
                number
            ] | null;
            /** State */
            state?: string | null;
            /** City */
            city?: string | null;
            /**
             * Specialty
             * @description Name of a specialty defined in the connectors config
             */
            specialty?: string | null;
            /**
             * Conditions
             * @description Codes of conditions; the patient must have ANY of them
             */
            conditions?: string[];
            /**
             * Procedures
             * @description Codes of procedures; the patient must have had ANY of them (combined with conditions by AND)
             */
            procedures?: string[];
            /**
             * Match
             * @description How conditions and procedures combine: 'all' = the patient needs a matching condition AND a matching procedure; 'any' = either one is enough (e.g. a specialty: has the disease OR had the operation)
             * @default all
             * @enum {string}
             */
            match: "all" | "any";
            /**
             * Medications
             * @description RxNorm codes of medications the patient is CURRENTLY taking at the end of the simulated period (combined with conditions/procedures by `match`). Find codes with the term search
             */
            medications?: string[];
            /**
             * Within
             * @description How the codes inside conditions (and inside procedures) combine: 'any' = at least one of them; 'all' = every one of them (comorbidity, e.g. diabetes AND hypertension)
             * @default any
             * @enum {string}
             */
            within: "any" | "all";
            /** Years Of History */
            years_of_history?: number | null;
            /** Only Alive */
            only_alive?: boolean | null;
        };
        /** ComponentInfo */
        ComponentInfo: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Params Schema */
            params_schema?: {
                [key: string]: unknown;
            } | null;
        };
        /** ConnectorHealthResponse */
        ConnectorHealthResponse: {
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /** ConnectorInfo */
        ConnectorInfo: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Enabled */
            enabled: boolean;
            /** Native Filters */
            native_filters?: string[] | null;
            /** Fhir Versions */
            fhir_versions?: string[] | null;
            /** Deterministic */
            deterministic?: boolean | null;
        };
        /** GenerationOptions */
        GenerationOptions: {
            /**
             * Check References
             * @description Fail the job if the output contains references that do not resolve
             * @default false
             */
            check_references: boolean;
        };
        /**
         * GenerationRequest
         * @description What the API accepts. Every field is optional: give a preset, or a full spec, or a preset + overrides.
         * @example {
         *       "cohort": {
         *         "count": 2,
         *         "seed": 42
         *       },
         *       "preset": "full-patient"
         *     }
         */
        GenerationRequest: {
            /** Preset */
            preset?: string | null;
            /** Connector */
            connector?: string | null;
            cohort?: components["schemas"]["CohortOverrides"] | null;
            /** Shape */
            shape?: components["schemas"]["ShapeStep"][] | null;
            sink?: components["schemas"]["SinkSpec"] | null;
            options?: components["schemas"]["GenerationOptions"] | null;
            /**
             * Connector Params
             * @description Per-request overrides the connector explicitly allows (Synthea: reference_date, end_date, and a safe subset of properties such as exporter.fhir.use_us_core_ig). Anything else is rejected.
             */
            connector_params?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * GenerationResultResponse
         * @description Returned by POST /generations. `data` carries the bundles for inline sinks.
         */
        GenerationResultResponse: {
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "expired";
            /** Connector */
            connector?: string | null;
            /** Preset */
            preset?: string | null;
            /** Request */
            request: {
                [key: string]: unknown;
            };
            /** Resolved Spec */
            resolved_spec: {
                [key: string]: unknown;
            };
            /** Provenance */
            provenance?: {
                [key: string]: unknown;
            } | null;
            /** Summary */
            summary?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: {
                [key: string]: unknown;
            } | null;
            /**
             * Artifacts
             * @default []
             */
            artifacts: components["schemas"]["ArtifactResponse"][];
            /** Created At */
            created_at?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /** Data */
            data?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobResponse */
        JobResponse: {
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "expired";
            /** Connector */
            connector?: string | null;
            /** Preset */
            preset?: string | null;
            /** Request */
            request: {
                [key: string]: unknown;
            };
            /** Resolved Spec */
            resolved_spec: {
                [key: string]: unknown;
            };
            /** Provenance */
            provenance?: {
                [key: string]: unknown;
            } | null;
            /** Summary */
            summary?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: {
                [key: string]: unknown;
            } | null;
            /**
             * Artifacts
             * @default []
             */
            artifacts: components["schemas"]["ArtifactResponse"][];
            /** Created At */
            created_at?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /** PaginatedJobResponse */
        PaginatedJobResponse: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Data */
            data: components["schemas"]["JobResponse"][];
        };
        /** PlacesResponse */
        PlacesResponse: {
            /** State */
            state?: string | null;
            /** Items */
            items: string[];
        };
        /** PresetInfo */
        PresetInfo: {
            /** Name */
            name: string;
            /** Title */
            title?: string | null;
            /** Category */
            category?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
            /** Connector */
            connector?: string | null;
            /**
             * Cohort
             * @default {}
             */
            cohort: {
                [key: string]: unknown;
            };
            /** Shape */
            shape?: {
                [key: string]: unknown;
            }[] | null;
            /** Sink */
            sink?: {
                [key: string]: unknown;
            } | null;
        };
        /** PreviewResponse */
        PreviewResponse: {
            resolved_spec: components["schemas"]["ResolvedSpec"];
            /**
             * Mode
             * @enum {string}
             */
            mode: "sync" | "async";
            /** Warnings */
            warnings: string[];
        };
        /**
         * ResolvedSpec
         * @description Fully concrete: nothing left to look up in config except component options.
         */
        ResolvedSpec: {
            /** Connector */
            connector: string;
            cohort: components["schemas"]["CohortSpec"];
            /** Shape */
            shape: components["schemas"]["ShapeStep"][];
            sink: components["schemas"]["SinkSpec"];
            options?: components["schemas"]["GenerationOptions"];
            /** Connector Params */
            connector_params?: {
                [key: string]: unknown;
            };
            /** Preset */
            preset?: string | null;
            /** Warnings */
            warnings?: string[];
        };
        /** ShapeStep */
        ShapeStep: {
            /** Slicer */
            slicer: string;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
        };
        /** SinkSpec */
        SinkSpec: {
            /** Name */
            name: string;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
        };
        /** TermInfo */
        TermInfo: {
            /** Kind */
            kind: string;
            /** System */
            system: string;
            /** Code */
            code: string;
            /** Display */
            display: string;
            /** Modules */
            modules: string[];
            /** Reference */
            reference: string;
        };
        /** TermSearchResponse */
        TermSearchResponse: {
            /** Total */
            total: number;
            /** Returned */
            returned: number;
            /** Items */
            items: components["schemas"]["TermInfo"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_generations: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_generation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationResultResponse"];
                };
            };
            /** @description Job queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_generation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_generation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Generation or artifact not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_generation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Generation or artifact not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_generation_artifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/octet-stream": unknown;
                };
            };
            /** @description Generation or artifact not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_generation_bundles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundleIndexResponse"];
                };
            };
            /** @description Generation or artifact not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_generation_bundle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Generation or artifact not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_connectors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorInfo"][];
                };
            };
        };
    };
    connector_health: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorHealthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_terms: {
        parameters: {
            query?: {
                /** @description Words to look for in the term name, its code, or its Synthea module */
                q?: string | null;
                kind?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_places: {
        parameters: {
            query?: {
                /** @description Return this state's cities instead of the list of states */
                state?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_resource_groups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    list_slicers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentInfo"][];
                };
            };
        };
    };
    list_sinks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentInfo"][];
                };
            };
        };
    };
    list_specialties: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_presets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetInfo"][];
                };
            };
        };
    };
    get_preset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_preset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GenerationRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
