"""Pure functions: (cohort, options) -> Synthea command-line arguments and keep-module JSON.
No I/O, so they are unit-testable without Docker or Java.

Verified against Synthea v4.0.0 (`run_synthea -h`, plus real runs):
  [-s seed] [-cs clinicianSeed] [-p populationSize] [-r referenceDate YYYYMMDD]
  [-g gender] [-a minAge-maxAge] [-d localModulesDirPath] [-k keepMatchingPatientsPath]
  [--<property>=value]  [state [city]]
`-p` is the number of *alive* patients to produce; a keep module (-k) discards patients
who do not reach a state named "Keep", and Synthea keeps generating until -p are kept.
"""

import re
from typing import Any

from app.generator.errors import InvalidSpecError
from app.generator.spec import CohortSpec

# Docker mode: the per-job workdir is bind-mounted at DOCKER_WORK, custom modules at DOCKER_MODULES.
# Local mode passes real host paths instead. Either way Synthea writes under <work>/output.
DOCKER_WORK = "/work"
DOCKER_MODULES = "/modules"
KEEP_MODULE_FILE = "keep.json"

# A bare code must be numeric (SNOMED-CT is assumed); alphanumeric codes (ICD-10 "C25.0") need an explicit system.
_CONDITION_RE = re.compile(
    r"^(?:(?P<system>[A-Za-z][A-Za-z0-9_-]*):(?P<code>[A-Za-z0-9][A-Za-z0-9.\-]*)|(?P<bare>\d+))$"
)
_PROPERTY_KEY_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_]*(\.[A-Za-z0-9_]+)+$")
# Properties the connector owns; letting a caller set them would break output handling.
RESERVED_PROPERTIES = {
    "exporter.baseDirectory",
    "exporter.fhir.export",
    "exporter.hospital.fhir.export",
    "exporter.practitioner.fhir.export",
    "generate.only_alive_patients",
    "exporter.years_of_history",
}


def parse_condition(text: str, default_system: str = "SNOMED-CT") -> tuple[str, str]:
    """'44054006' or 'SNOMED-CT:44054006' or 'ICD10:C25.0' -> (system, code)."""
    match = _CONDITION_RE.match(text.strip())
    if not match:
        raise InvalidSpecError(
            f"Invalid code '{text}'. Use a numeric SNOMED code ('44054006') or SYSTEM:CODE ('ICD10:C25.0', "
            "'SNOMED-CT:44054006'). Find codes with GET /connectors/synthea/terms?q=..."
        )
    if match.group("bare"):
        return default_system, match.group("bare")
    return match.group("system"), match.group("code")


def _combine(
    codes: list[str], within: str = "any", condition_type: str = "Active Condition", default_system: str = "SNOMED-CT"
) -> dict[str, Any]:
    """Condition matching ANY (or, with within="all", EVERY) one of the codes. Procedures use `Active Condition` too: Synthea records performed
    procedures in the same "present" map and never removes them (the trick its own must_have_cabg.json uses)."""
    parts = []
    for text in codes:
        system, code = parse_condition(text, default_system)
        parts.append(
            {
                "condition_type": condition_type,
                "codes": [{"system": system, "code": code, "display": f"{system} {code}"}],
            }
        )
    return {"condition_type": "And" if within == "all" else "Or", "conditions": parts}


def build_keep_module(
    conditions: list[str],
    procedures: list[str] | None = None,
    match: str = "all",
    within: str = "any",
    medications: list[str] | None = None,
) -> dict[str, Any]:
    """Synthea 'keep module' (generic module format): the patient is exported only if they have ANY of the
    listed conditions AND (match="all") / OR (match="any") ANY of the listed procedures. Same shape as Synthea's own
    keep_modules/keep_diabetes.json and must_have_cabg.json."""
    groups = [_combine(g, within) for g in (conditions, procedures or []) if g]
    if medications:  # "Active Medication": being on the drug at the end of the simulation (RxNorm by default)
        groups.append(_combine(medications, within, "Active Medication", "RxNorm"))
    joiner = "Or" if match == "any" else "And"
    condition = groups[0] if len(groups) == 1 else {"condition_type": joiner, "conditions": groups}
    return {
        "name": "Generated keep module",
        "remarks": ["Generated by fhir-synthetic-data-generator: keep patients matching the conditions/procedures"],
        "states": {
            "Initial": {
                "type": "Initial",
                "conditional_transition": [
                    {"transition": "Keep", "condition": condition},
                    {"transition": "Terminal"},
                ],
            },
            "Terminal": {"type": "Terminal"},
            "Keep": {"type": "Terminal"},
        },
        "gmf_version": 2,
    }


def _prop_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def validate_properties(properties: dict[str, Any]) -> None:
    for key, value in properties.items():
        if not _PROPERTY_KEY_RE.match(key):
            raise InvalidSpecError(f"Invalid Synthea property name '{key}'")
        if key in RESERVED_PROPERTIES:
            raise InvalidSpecError(
                f"Synthea property '{key}' is managed by the connector and cannot be set in options"
            )
        if not isinstance(value, (str, int, float, bool)):
            raise InvalidSpecError(f"Synthea property '{key}' must be a scalar value")


# What a REQUEST may set via connector_params.properties (config can set anything). Narrow on purpose:
# FHIR export flavour and generation tuning only; never paths, never the properties the connector owns.
REQUEST_PROPERTY_PREFIXES = ("exporter.fhir.", "generate.")
_REQUEST_FORBIDDEN = RESERVED_PROPERTIES | {"exporter.fhir.bulk_data"}  # bulk_data changes the output layout
_REQUEST_VALUE_RE = re.compile(r"^[A-Za-z0-9_.\-]{1,64}$")


def validate_request_properties(properties: dict[str, Any]) -> None:
    validate_properties(properties)
    for key, value in properties.items():
        if not key.startswith(REQUEST_PROPERTY_PREFIXES) or key in _REQUEST_FORBIDDEN:
            raise InvalidSpecError(
                f"Synthea property '{key}' cannot be set per request. Allowed prefixes: "
                f"{', '.join(REQUEST_PROPERTY_PREFIXES)} (except connector-managed ones and exporter.fhir.bulk_data)"
            )
        if isinstance(value, str) and not _REQUEST_VALUE_RE.match(value):
            raise InvalidSpecError(f"Value for '{key}' has unsupported characters")


def build_synthea_args(
    cohort: CohortSpec,
    *,
    reference_date: str,
    end_date: str | None,
    default_state: str,
    years_of_history: int | None,
    properties: dict[str, Any],
    work: str,
    has_keep_module: bool,
    modules_path: str | None,
    jar: str,
    jvm_args: list[str],
) -> list[str]:
    """The `java ...` command line (without the leading `java`/docker wrapper)."""
    args = [*jvm_args, "-jar", jar]
    seed = cohort.seed if cohort.seed is not None else 0
    args += ["-p", str(cohort.count), "-s", str(seed), "-cs", str(seed), "-r", reference_date]
    if end_date:
        args += ["-e", end_date]
    if cohort.gender:
        args += ["-g", cohort.gender]
    if cohort.age_range:
        args += ["-a", f"{cohort.age_range[0]}-{cohort.age_range[1]}"]
    if has_keep_module:
        args += ["-k", f"{work}/{KEEP_MODULE_FILE}"]
    if modules_path:
        args += ["-d", modules_path]

    args += [
        f"--exporter.baseDirectory={work}/output",
        "--exporter.fhir.export=true",
        "--exporter.hospital.fhir.export=true",
        "--exporter.practitioner.fhir.export=true",
    ]
    history = cohort.years_of_history if cohort.years_of_history is not None else years_of_history
    if history is not None:
        args.append(f"--exporter.years_of_history={history}")
    # Deceased patients are dropped unless the caller explicitly asks for them (only_alive: false),
    # so that `count` means "patients exported".
    if cohort.only_alive is not False:
        args.append("--generate.only_alive_patients=true")
    for key, value in sorted(properties.items()):
        args.append(f"--{key}={_prop_value(value)}")

    args.append(cohort.state or default_state)
    if cohort.city:
        args.append(cohort.city)
    return args
