/** One colour per kind of resource, shared by the nodes, the legend and the side panel. Mid-lightness so it reads on light and dark. */
const COLORS = {
  patient: "oklch(0.62 0.17 255)",
  visit: "oklch(0.62 0.18 295)",
  diagnosis: "oklch(0.64 0.19 20)",
  procedure: "oklch(0.7 0.16 70)",
  medication: "oklch(0.66 0.15 150)",
  vaccine: "oklch(0.66 0.12 190)",
  result: "oklch(0.68 0.12 225)",
  plan: "oklch(0.6 0.16 275)",
  order: "oklch(0.7 0.17 50)",
  money: "oklch(0.6 0.04 250)",
  document: "oklch(0.6 0.02 250)",
  device: "oklch(0.7 0.15 125)",
  provider: "oklch(0.62 0.03 60)",
} as const;

const BY_TYPE: Record<string, keyof typeof COLORS> = {
  Patient: "patient",
  Encounter: "visit",
  Condition: "diagnosis",
  AllergyIntolerance: "diagnosis",
  Procedure: "procedure",
  MedicationRequest: "medication",
  MedicationAdministration: "medication",
  Medication: "medication",
  Immunization: "vaccine",
  Observation: "result",
  DiagnosticReport: "result",
  ImagingStudy: "result",
  Media: "result",
  CarePlan: "plan",
  CareTeam: "plan",
  Goal: "plan",
  ServiceRequest: "order",
  Claim: "money",
  ExplanationOfBenefit: "money",
  Coverage: "money",
  DocumentReference: "document",
  Provenance: "document",
  Device: "device",
  SupplyDelivery: "device",
  Practitioner: "provider",
  PractitionerRole: "provider",
  Organization: "provider",
  Location: "provider",
};

export const typeColor = (type: string): string => COLORS[BY_TYPE[type] ?? "document"];
